name: Deploy Container

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: docker/login-action@v1
        with:
          registry: overvoltage.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: nix build .#container
      - run: docker load < ./result
      - run: docker tag overvoltage overvoltage.azurecr.io/overvoltage:$(nix eval --raw .#overvoltage.version)
      - run: docker push overvoltage.azurecr.io/overvoltage
