name: Deploy Container

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Log in to Azure ACR
        uses: docker/login-action@v1
        with:
          registry: overvoltage.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Build image
        run: nix build .#container
      - name: Get version
        run: echo "VERSION=$(nix eval --raw .#overvoltage.version)" >> $GITHUB_ENV
      - name: Load image
        run: docker load < ./result
      - name: Tag image
        run: docker tag "overvoltage:$VERSION" "overvoltage.azurecr.io/overvoltage:$VERSION"
      - name: Push image
        run: docker push "overvoltage.azurecr.io/overvoltage:$VERSION"
